close #16 課題提出(kodama)
KatLab-MiyazakiUniv/learn-github-2021 pull request #17
Opened 2021-05-10 07:47 UTC by kodama0720

# 変更点
- Direction.cppを追加した
- gitkeepを削除した

2021-05-10 07:59 UTC, Hisataka-Hagiyama approved these changes
LGTM

2021-05-11 03:28 UTC, mutotaka0426 commented on kodama/Direction.cpp
> +* @author 児玉 github名
```suggestion
* @author kodama0728
```

2021-05-11 03:29 UTC, mutotaka0426 commented on kodama/Direction.cpp
> +#include "Direction.h"
ヘッダーファイルに分けてるならそっちもあげてください

2021-05-11 06:01 UTC, mutotaka0426 requested changes

2021-05-11 06:01 UTC, mutotaka0426 commented on kodama/Direction.h
> +#define PID_H
ヘッダーファイルの名前と合わせようか
```suggestion
#ifndef DIRECTION_H
#define DIRECTION_H
```

2021-05-11 06:15 UTC, mutotaka0426 approved these changes
![LGTM](https://image.lgtmoon.dev/26551)

2021-05-11 06:23 UTC, merged